# Rubocop configuration based on the Relaxed Ruby Style (with some changes).

AllCops:
  TargetRubyVersion: 2.4

Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
