inherit_from:
  - http://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Max: 100
Style/NumericPredicate:
  # Dumb, but also brand new.
  Enabled: false
Metrics/BlockLength:
  # Stop rubocop from complaining about large `describe` blocks.
  Exclude:
    - spec/**/*_spec.rb
