AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

# Dumb, but also brand new.
Style/NumericPredicate:
  Enabled: false

# Stop rubocop from complaining about large `describe` blocks.
Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

# Lower severity of complexity metrics.
Metrics/AbcSize:
  Severity: refactor
Metrics/CyclomaticComplexity:
  Severity: refactor
Metrics/PerceivedComplexity:
  Severity: refactor
